### PR TITLE
chore: rewrite package for Adonis 5

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
Is there an example somewhere on how to write tests for a provider?

**Comment by RomainLanz** [comment]
I believe we should also add an `instructions.ts` file that will ask the user which driver he want to installed (`GCS` and `S3`).

This would install the package in user-land and also add the configuration.
An example could be find here: https://github.com/Slynova-Org/symfony-encore/blob/master/instructions.ts

**Comment by targos** [comment]
I added the instructions file.

**Comment by targos** [comment]
What are the next steps?

**Comment by LeCoupa** [comment]
Any idea when this PR will be merged?

**Review by RomainLanz — APPROVED** [review]

**Comment by irwing-reza** [comment]
Any updates?

**Pull request closed without merging**
